name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip git zip openjdk-17-jdk
        pip3 install --user buildozer cython kivy plyer

    - name: Initialize Buildozer
      run: buildozer init

    - name: Modify Buildozer Spec
      run: |
        sed -i 's|package.name = .*|package.name = PrankApp|' buildozer.spec
        sed -i 's|package.domain = .*|package.domain = com.arya|' buildozer.spec
        sed -i 's|android.permissions = .*|android.permissions = VIBRATE, INTERNET, WAKE_LOCK|' buildozer.spec
        sed -i 's|android.arch = .*|android.arch = arm64-v8a|' buildozer.spec
        sed -i 's|# android.ndk = .*|android.ndk = 23b|' buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: PrankApp-APK
        path: bin/*.apk
